### ISSUE TITLE
incorrect command + output in the docs

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#1]
https://redhat-developer-demos.github.io/tekton-tutorial/tekton-tutorial/tasks.html#tekton-task-step-template

instructs the reader to use this command
kubectl get pod -n tektontutorial build-app-run-bsr4k-pod-xbxwg\
-o=jsonpath="{range .spec.containers[*]} {.name} {'\n'} {.volumeMounts[?(@.name=='varlibc')]} {'\n'} {end}"

to produce the following results.  There should be yet another command.

 step-create-dir-builtimage-4jmh2
 map[privileged:true runAsUser:0]

 step-git-source-git-source-fgq4p
 map[privileged:true runAsUser:0]

 step-build-sources
 map[privileged:true runAsUser:0]

 step-build-image
 map[privileged:true runAsUser:0]

 step-push-image
 map[privileged:true runAsUser:0]

 step-image-digest-exporter-8g4ss
 map[privileged:true runAsUser:0]

**Comment by kameshsampath** [comment]
@sebastienblanc  can you fix this when you play with Tekton today/tomorrow ?

**Comment by kameshsampath** [comment]
Fixed via 45d705c
