### ISSUE TITLE
Error from server (BadRequest): error when creating "build-resources.yaml": admission webhook "webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "managedFields"

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#11]
result of using "kubectl apply -n tektontutorial -f build-resources.yaml"

tkn version
Client version: 0.8.0
Pipeline version: v0.10.2

**Comment by burrsutter** [comment]
The issue is related to Kubernetes 1.18.  The current start-minikube.sh script does not specify the Kubernetes version therefore it picks up whatever is latest & greatest.   I changed my local copy of the script to be in-line with what we have for Kube Tutorial and Istio Tutorial 
minikube start -p $PROFILE_NAME \
  --memory=$MEMORY --cpus=$CPUS \
  --disk-size=50g \
  --vm-driver=virtualbox \
  --kubernetes-version=v1.17.4 \
  --insecure-registry='10.0.0.0/24'

**Comment by kameshsampath** [comment]
possibly using wrong version of kubectl and tekton version. I updated to the 0.11.3 of Tekton and it works with minikube latest + kubectl 1.18.x. 0.11.3 is the version deployed as part of Openshift Pipelines Operator.
