### ISSUE TITLE
Reader needs to know to hit Enter

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#12]
tkn task start source-lister
prompts for contextDir
https://www.screencast.com/t/9CxAuY9Xr

the end-user needs to be told to hit Enter on their keyboard to accept the defaults

**Comment by kameshsampath** [comment]
This is too much a ask in a tutorial to say you press enter to continue.. if the user is that dumb then he needs to get to his computer basics class 😁

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kameshsampath** [comment]
Fixed via 6b97fc8
