### ISSUE TITLE
Listing the tasks in the customertask-demo will not show any Tasks as shown in the command output below.

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#13]
kubectl create namespace clustertask-demo &&\
kubectl config set-context --current --namespace clustertask-demo

customertask-demo vs clustertask-demo

https://redhat-developer-demos.github.io/tekton-tutorial/tekton-tutorial/tasks.html#tekton-task-list-ws

**Comment by kameshsampath** [comment]
Fixed via 6b97fc8
