### ISSUE TITLE
2 commands instead of 1

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#14]
in this section 
https://redhat-developer-demos.github.io/tekton-tutorial/tekton-tutorial/tasks.html#tekton-task-list-ws
this should be two commands instead of one
kubectl config set-context --current --namespace=tektontutorial && \
tkn clustertask start echoer --showlog

2 steps would ease the learning factor

**Comment by kameshsampath** [comment]
Fixed via 6b97fc8
