### ISSUE TITLE
usability enhancement: tkn tr logs -f -a $(`kubectl get pod -l tekton.dev/task=git-clone -o name`)

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#16]
There are several places where the end-user has to use the name/id of the pod that was launched.  
https://redhat-developer-demos.github.io/tekton-tutorial/tekton-tutorial/workspaces.html#ws-use-pvc-git-clone
"tkn tr logs -f -a git-clone-dpd7t"
and this line could be replaced with something that is copy & paste friendly like
tkn tr logs -f -a $(`kubectl get pod -l tekton.dev/task=git-clone -o name`)

right now, if the end-user does the copy the command will fail because the pod name is different.

**Comment by kameshsampath** [comment]
Thats a great point, using something like this now:

TaskRun logs:

```shell
tkn tr logs -f -a $(tkn tr ls -n {chapter-namespace} | awk 'NR==2{print $1}')
```

PipelineRun logs:

```shell
tkn pr logs -f -a $(tkn pr ls -n {chapter-namespace} | awk 'NR==2{print $1}')
```

Closed via 04f3bb9
