### ISSUE TITLE
missing wget from the pre-reqs

### ISSUE THREAD

**Issue by burrsutter** [redhat-developer-demos/tekton-tutorial#17]
https://redhat-developer-demos.github.io/tekton-tutorial/tekton-tutorial/setup.html#tekton-prerequisites

wget is used in the workspaces chapter
https://redhat-developer-demos.github.io/tekton-tutorial/tekton-tutorial/workspaces.html#ws-create-pipeline

brew install wget for MacOS

**Comment by kameshsampath** [comment]
Replaced with curl via 04f3bb9
